services:
  - type: web
    name: zayani-inspection-app
    env: node
    plan: free
    buildCommand: npm install && cd client && npm install && npm run build
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20.18.0
